### ISSUE TITLE
Add support for deleting keys

### ISSUE THREAD

**Issue by luisdavim** [iwanbk/bcache#20]
Hi, would it be possible to expose a `Delete` method?

**Comment by iwanbk** [comment]
yes, sure. I will be more than happy to implement it.
Didn't expect an outsider already found my lib :)

**Comment by luisdavim** [comment]
Awesome, thanks.

**Comment by iwanbk** [comment]
Just an update, i'm currently working to improve the test https://github.com/iwanbk/bcache/commits/peer-test

I think it is better before i add new feature.

**Comment by iwanbk** [comment]
The deletion work is in progress at `delete` branch https://github.com/iwanbk/bcache/commits/delete

**Comment by iwanbk** [comment]
a WIP PR could be found at #22, still needs some docs and might be more tests

**Comment by iwanbk** [comment]
@luisdavim i've merged this PR for this `delete` feature.
Also relese this lib as v0.1.
