### ISSUE TITLE
Delete key in underlying cache when calling Delete API

### ISSUE THREAD

**Issue by iwanbk** [iwanbk/bcache#23]
When calling `Delete` API we currently only mark it as delete,  not delete the key from underlying cache.

The reason is that i'm still not sure when is the safe time to delete it.

Consider this example situation, when we have three nodes:
- Node 2 has network issue, make it unreachable by the others
- Node 1 delete they key A
- Node 1 broadcasts the change
- Node 3 got the change

What happens to node 2 when it become reachable again, will it see the change? Will `mesh` handle it for us?

If we only marked it as deleted, the state will be kept by node 1 & node 3, and it will reach eventual consistency (to node 2) as promised by `mesh` library that used by `bcache`.

**Comment by iwanbk** [comment]
Note that the underlying cache is LRU cache with max keys, so it won't going to unlimited number of keys

**Comment by luisdavim** [comment]
What about delaying the actual removal to when we try to get a deleted key? Or a garbage collector,  similar to what redis does? Every x seconds it picks some random keys and if they are expired they get removed,  in this case instead of looking for expired keys we'd look for keys marked as deleted.

**Comment by luisdavim** [comment]
https://redis.io/commands/expire#appendix-redis-expires

**Comment by iwanbk** [comment]
@luisdavim many thanks for the suggestion and the link, i'll definitely look into it.

The way expiration work this way is because my use case actually doesn't need any expiration.

But thinking about it again, `bcache` will get more usage if it has similar behaviour with other common caches, it might need some API changes, but i think it is worth to do.

**Comment by iwanbk** [comment]
my plan for v0.2

key points:
- expiration will be handled by bcache, unlike v0.1 which basically do nothing with expiration
- passive key deletion. No GC-like mechanism at this phase, could be added later if needed
- `deletion delay`: add delay before delete the key, it  is used to handle temporary network connection issue, which prevent data syncing  between nodes
- specify `ttl` instead of `expirationTimestamp`. `expiration timestamp` in this new mechanism is error prone. (e.g.: use `time.Now().Unix()` instead of `time.Now().UnixNano()`)


API changes:
- Set(key, val string, ttl int): 
    - ttl in seconds with no default value.
    - ttl <=0 make it expired instantly
- Get(key string) (val string, exists bool)
- Delete(key string, deleteDelay int): 
    - `deleteDelay` in seconds
    - `deleteDelay` default valut is 300 seconds
    - `deleteDelay` could also be added in `Config` passed to `New`


Let me know if you have any comments @luisdavim

**Comment by luisdavim** [comment]
Sounds like a solid plan.
